name: clusterpaperifg

profile: clusterpaperifg

model-paths: ["models"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  stage_papers_year: "2019_2020"

models:
  clusterpaperifg:
    +file_format: delta
    # Materialize staging models as views, and marts as tables
    0_stage:
      +schema: stage
      +materialized: table
      +tags: ["stage"]

    1_bronze:
      +schema: bronze
      +materialized: view
      +tags: ["bronze"]

    2_silver:
      +schema: silver
      +materialized: table
      +tags: ["silver"]
    
    3_gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
    
snapshots:
  clusterpaperifg:
    +file_format: delta
